services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
#      dockerfile: nginx/DockerfileSSL # Uncomment if ssl certificate is available
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
#      - "443:443"  # Uncomment if ssl is enabled
    env_file:
      - .env
#    Uncomment if ssl certificate is available and comment next command
#    command: /bin/sh -c "envsubst < /etc/nginx/sites-enabled/forkrecipes-ssl.nginx.template > /etc/nginx/sites-enabled/forkrecipes.nginx.conf && nginx -g 'daemon off;'"
    command: /bin/sh -c "envsubst < /etc/nginx/sites-enabled/forkrecipes.nginx.template > /etc/nginx/sites-enabled/forkrecipes.nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/forkapi/static/:ro
      - web_media:/forkapi/media/
      - web_static_fe:/fork_recipes/static/:ro
    depends_on:
      - web
      - be


  be:
    image: mikebgrep/forkapi:latest
    container_name: forkapi
    hostname: forkapi-host
    env_file:
      - .env
    restart: always
    network_mode: "host"
    command: >
      sh -c "uwsgi --ini uwsgi.ini --chown-socket=www-data:www-data"
    volumes:
      - data:/forkapi/sql/
      - uwsgi_data:/tmp/uwsgi/
      - web_media:/forkapi/media/
      - web_static:/forkapi/static/


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipes
    image: forkrecipes:latest
    env_file:
      - .env
    restart: always
    network_mode: "host"
    command: >
      sh -c "uwsgi --ini uwsgi.ini --chown-socket=www-data:www-data"
    volumes:
      - data:/fork_recipes/sql/
      - uwsgi_data:/tmp/uwsgi/
      - web_static_fe:/fork_recipes/static/
    depends_on:
      - be


volumes:
  data:
  uwsgi_data:
  web_static:
  web_media:
  web_static_fe:
