# Generated by Django 5.0.2 on 2024-11-12 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('video', models.URLField(blank=True, null=True)),
                ('time', models.CharField(max_length=50)),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20)),
                ('chef', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Desserts', 'Desserts'), ('Vegetarian', 'Vegetarian')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
