# Generated by Django 5.0.2 on 2024-11-13 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_upload',
            field=models.FileField(blank=True, default=None, null=True, upload_to='recipe_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])]),
        ),
    ]
